[app]
name = "GraymeBadge"
category = "Badge"
wifi_preference = false

[entry]
class = "GraymeBadge"

[metadata]
author = "AgentAntelope"
license = "Unlicense"
description = "A greyscale 'Hello my name is' sticker style Tildagon name badge. Rendering based on jake-walker's"
version = "0.0.2"
